import { Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";

// Load local font but do NOT apply globally
const myCustomFont = localFont({
  src: "../../public/fonts/Megafont.ttf",
  variable: "--font-custom", // Define variable but don't apply it globally
  display: "swap",
});

// Keep Geist Mono as the global font
const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata = {
  title: "Artofqr",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistMono.variable}`}
    >
      <head />
      <body className="font-geist-mono">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
